version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing HashiCorp Packer....."
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/0.12.3/packer_0.12.3_linux_amd64.zip && unzip packer.zip
      - echo "Installing jq..."
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq 
      - mv packer /usr/local/bin
      - pwd 
      - ls -lrt $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR/infra/packer/
      - echo "Validating packer.json"
      - packer validate packer.json
  
  build:
    commands:
      - echo "Configuring AWS credentials"
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id `jq -r ' .AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `jq -r ' .SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `jq -r '.Token' aws_credentials.json`
      - cat aws_credentials.json
      - echo "Building HashiCorp Packer template, codewithkesav.json"
      - packer build packer.json

  post_build:
     commands:
      - echo "HashiCorp Packer Build Completed on `date`" 
